FROM node:latest
WORKDIR /app
COPY . .
#COPY ./package.json ./
#COPY ./package-lock.json ./
#RUN npm ci
#RUN npm run build
RUN yarn
COPY . ./
#RUN #yarn build
RUN yarn install --frozen-lockfile
CMD ["npm", "start"]