version: "3.9"
services:

  # api:
  #   build:
  #     context: ./api
  #   ports:
  #   - 8000:8000
  #   volumes:
  #   - ./api:/api
  #   env_file:
  #     - ./api/.env
  
  db:
    image: postgis/postgis
    volumes:
      - postgis-data:/var/lib/postgresql/data
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - TZ=America/Denver
      - PGTZ=America/Denver
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgis-data: