# Production Docker Compose
# Uses remote database - see configuration in api/.env_production

version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile_production
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - api
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`pvacd.newmexicowaterdata.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure,web"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

      # - "traefik.http.routers.frontend-insecure.middlewares=force-secure"
      # - "traefik.http.middlewares.force-secure.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.force-secure.redirectscheme.permanent=true"
  
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "
        uvicorn api.main:app 
        --host 0.0.0.0 
        --proxy-headers --root-path /api/v1
      "
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - traefik
    env_file:
      - ./api/.env_production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`pvacd.newmexicowaterdata.org`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=api-sp"
      - "traefik.http.middlewares.api-sp.stripprefix.prefixes=/api/v1"
      - "traefik.http.middlewares.api-sp.stripprefix.forceSlash=false"
      - "traefik.http.routers.api-insecure.rule=Host(`pvacd.newmexicowaterdata.org`) && PathPrefix(`/api/v1`)"
      - "traefik.http.routers.api-insecure.entrypoints=web"

      # - "traefik.http.routers.api-insecure.middlewares=force-secure"
      # - "traefik.http.middlewares.force-secure.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.force-secure.redirectscheme.permanent=true"

  traefik:
    image: "traefik:v2.9"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

      # for production deployment testing  make sure the next line is uncommented. Comment out once you know all app components are working
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=newmexicowaterdata@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
#      - "--traefik.http.middlewares.force-secure.redirectscheme.scheme=https"
#      - "--traefik.http.middlewares.force-secure.redirectscheme.permanent=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  