# Use this to create a database that is a copy of a backup of the production database

version: "3.9"
services:

  db:
    env_file:
      - ./api/.env_local
    image: postgis/postgis
    volumes:
      - postgis-data:/var/lib/postgresql
      - ./api/backupdb/appdb.sql:/appdb.sql
      - ./api/backupdb/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - TZ=America/Denver
      - PGTZ=America/Denver
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  postgis-data:
