INSERT INTO
    public."LandOwners" (
        id,
        contact_name,
        organization,
        address,
        city,
        state,
        zip,
        phone,
        mobile,
        email,
        note
    )
VALUES
    (
        '1',
        NULL,
        'AG SERVICES',
        '1905 OLD DEXTER HIGHWAY',
        'ROSWELL',
        'NM',
        '88203',
        '575-626-4939',
        NULL,
        NULL,
        'NEAL POPE AND RAY POPE'
    ),
    (
        '2',
        NULL,
        'AIRGAS',
        '1103 EAST SECOND ST',
        'ROSWELL',
        'NM',
        '88201',
        '575-622-1950',
        NULL,
        NULL,
        NULL
    ),
    (
        '3',
        NULL,
        'AMERICAN OXYGEN CO., INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '4',
        NULL,
        'ARMSTRONG & SON, LLC',
        'P.O. BOX 1973',
        'ROSWELL',
        'NM',
        '88202',
        '575-622-1080',
        NULL,
        NULL,
        NULL
    ),
    (
        '5',
        NULL,
        'ARTESIA COUNTRY CLUB',
        'P.O. BOX 1305',
        'ARTESIA',
        'NM',
        '88211',
        '575-746-2055',
        NULL,
        NULL,
        NULL
    ),
    (
        '6',
        NULL,
        'ARTESIA DAILY PRESS',
        'PO DRAWER 190',
        'ARTESIA',
        'NM',
        '88211-0190',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '7',
        NULL,
        'ARTESIA LUMBER CO.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '8',
        NULL,
        'ATKINS ENGINEERING ASSOCIATES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '9',
        NULL,
        'AWC PROPANE COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '10',
        NULL,
        'BAKER UTILITY SUPPLY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '11',
        NULL,
        'BELL GAS, INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '12',
        NULL,
        'BEN KERR',
        '7152 CHEROKEE RD.',
        'DEXTER',
        'NM',
        '88230',
        '575-626-9557',
        NULL,
        NULL,
        'SECRETARY-TREASURE OF THE BOARD DISTRICT 3'
    ),
    (
        '13',
        NULL,
        'BENNY & CINDY WOOTON',
        '1100 EAST 18TH ST.',
        'ROSWELL',
        'NM',
        '88201',
        '575-622-5580',
        '575-626-5754',
        NULL,
        NULL
    ),
    (
        '14',
        NULL,
        'BERNICE D''ABADIE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'DECEASED'
    ),
    (
        '15',
        NULL,
        'BERRENDO CO-OP WATER ASSN.',
        '2004 EAST 19TH ST.',
        'ROSWELL',
        'NM',
        '88201',
        '505-623-7665',
        NULL,
        NULL,
        'ACCTOUNT # J1-11'
    ),
    (
        '16',
        NULL,
        'BILL HORNER',
        '2406 N. HALDEMAN ROAD',
        'ARTESIA',
        'NM',
        '88210',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '17',
        NULL,
        'BILL NETHERLIN',
        '103 E FOUR DINKUS RD',
        'ARTESIA',
        'NM',
        '88210',
        '575-365-7400',
        NULL,
        NULL,
        'CHAIRMAN OF THE BOARD, DISTRICT 5'
    ),
    (
        '18',
        NULL,
        'BILLIE LANG - JERI HILLEY',
        '201 TIERRA BERRENDA DR',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        '575-317-6960',
        NULL,
        'JERI HAS POA OVER BILLIE LANG'
    ),
    (
        '19',
        NULL,
        'BLAINE HAINES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '20',
        NULL,
        'BOB FINCH',
        '40 DEBORAH DR',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        'LOAN # 265A'
    ),
    (
        '21',
        NULL,
        'BOB KUYKENDALL',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '22',
        NULL,
        'BOB REED PEST CONTROL',
        '1206 WEST HOBBS',
        'ROSWELL',
        'NM',
        '88203',
        '575-623-5344',
        NULL,
        NULL,
        'ACCT. # 200008011'
    ),
    (
        '23',
        NULL,
        'BOGLE LTD.',
        'PO DRAWER 460',
        'DEXTER',
        'NM',
        '88232',
        '575-734-5442',
        NULL,
        NULL,
        'LN # 261E-261G-261H-261D-261F-261C'
    ),
    (
        '24',
        NULL,
        'BORBA REVOCABLE TRUST',
        '3700 LOVER''S LANE',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '25',
        NULL,
        'BRENT D. BULLOCK',
        '4609 ACACIA',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-4480',
        NULL,
        NULL,
        'SUPERINTENDENT'
    ),
    (
        '26',
        NULL,
        'BRIAN AND GAYNETTE FREELAND',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '27',
        NULL,
        'BROWN & BROWN OF NM INC.-ROS',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '28',
        NULL,
        'BROWN BROTHERS RANCH',
        '3930 SOUTH BROWN RD',
        'ROSWELL',
        'NM',
        '88203',
        '575-623-5594',
        NULL,
        NULL,
        'LOAN # 266A --CELL: 575-734-5619'
    ),
    (
        '29',
        NULL,
        'CALEB AND BRADEN LEIGH WIDENER',
        '3779 EAST GRAND PLAINS RD',
        'ROSWELL',
        'NM',
        '88203',
        '575-765-0702',
        '575-626-2414',
        NULL,
        'CALEBWIDENER@GMAIL.COM'
    ),
    (
        '30',
        NULL,
        'CARLSBAD CURRENT-ARGUS',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '31',
        NULL,
        'CARRIE JACKSON',
        '72 WEST JACKSON ROAD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-2342',
        NULL,
        NULL,
        NULL
    ),
    (
        '32',
        NULL,
        'CECIL POLLARD',
        '435 JICARRILLA RD',
        'HAGERMAN',
        'NM',
        '88232',
        '575-752-3391',
        NULL,
        NULL,
        'LOAN # A340, 287A -287B-C287-D287-E287-F287-                     TIM''S CELL: 575-399-3598'
    ),
    (
        '33',
        NULL,
        'CHAMCO PROPERTIES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '34',
        NULL,
        'CHAMPION LAND AND CATTLE CO',
        '101 E BLEVINS RD',
        'ARTESIA',
        'NM',
        '88210',
        '575-748-3030',
        NULL,
        NULL,
        'LOAN # A296'
    ),
    (
        '35',
        NULL,
        'CHAMPION/ JOY',
        'PO BOX 928',
        'ARTESIA',
        'NM',
        '88211',
        '575-365-5052',
        NULL,
        NULL,
        NULL
    ),
    (
        '36',
        NULL,
        'CHAMPION/ JOY',
        'PO BOX 928',
        'ARTESIA',
        'NM',
        '88211',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '37',
        NULL,
        'CHARLES MARLEY',
        'PO BOX 592',
        'ROSWELL',
        'NM',
        '88202-0592',
        '575-623-2407',
        NULL,
        NULL,
        'LOAN # E230-230D'
    ),
    (
        '38',
        NULL,
        'CHASE FARMS',
        'PO BOX 658',
        'ARTESIA',
        'NM',
        '88210',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '39',
        NULL,
        'CHAVES COUNTY FLOOD CONTROL',
        'P.O. BOX 1817',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-1356',
        NULL,
        NULL,
        'SUPERINTENDENT'
    ),
    (
        '40',
        NULL,
        'CHAVES COUNTY TREASURER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '41',
        NULL,
        'CITY OF CARLSBAD',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '42',
        NULL,
        'CITY OF ROSWELL',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '43',
        NULL,
        'CLARA KING',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '44',
        NULL,
        'CLINT LYNCH',
        '560 AZTEC RD.',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-5319',
        NULL,
        NULL,
        NULL
    ),
    (
        '45',
        NULL,
        'COATS PUMP CO.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '46',
        NULL,
        'COATS REVOCABLE TRUST',
        'P. BOX 1210',
        'DEXTER',
        'NM',
        '88230',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '47',
        NULL,
        'CODY MUNSON',
        NULL,
        NULL,
        NULL,
        NULL,
        '626-0365',
        NULL,
        NULL,
        NULL
    ),
    (
        '48',
        NULL,
        'COTTONWOOD WATER CO-OP',
        NULL,
        'ARTESIA',
        'NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '49',
        NULL,
        'CSED/ CASH PROCESSING',
        'P.O. BOX 25109',
        'SANTA FE',
        'NM',
        '87504-5109',
        NULL,
        NULL,
        NULL,
        'CALLAWAY 6166112'
    ),
    (
        '50',
        NULL,
        'DAN LATHROP',
        '7375 SHOSHONI',
        'HAGERMAN',
        'NM',
        '88232',
        '575-734-5806',
        NULL,
        NULL,
        'LOAN # 278A'
    ),
    (
        '51',
        NULL,
        'Danny Castro',
        NULL,
        'Roswell',
        'nm',
        '88203',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '52',
        NULL,
        'Danny Castro',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '53',
        NULL,
        'DAVID AND TRACEY CORN',
        '471 STARGRASS RD',
        'ROSWELL',
        'NM',
        '88201',
        '575-625-2280',
        '575-420-0420',
        NULL,
        NULL
    ),
    (
        '54',
        NULL,
        'DAVID GLENN MILLER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '55',
        NULL,
        'DAVID MCCREA',
        'PO BOX 3359',
        'ROSWELL',
        'NM',
        '88202',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '56',
        NULL,
        'DAY FARMS',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '57',
        NULL,
        'DEAN LEE',
        'PO BOX 89',
        'LAKEWOOD',
        'NM',
        '88254',
        '575-365-6351',
        NULL,
        NULL,
        'BRANDON SMITH (NEPHEW) # 720-257-2801'
    ),
    (
        '58',
        NULL,
        'DENNIS A. KARNES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'TERMINATED!!!!!!!!'
    ),
    (
        '59',
        NULL,
        'DONNA KAY HIX',
        '3594 W COUNTY ROAD 6005',
        'CLAYTON',
        'ID',
        '46118',
        '317-605-4029',
        NULL,
        NULL,
        'RA 3461-B'
    ),
    (
        '60',
        NULL,
        'DOUBLE L FARMS',
        '343 WEST PEARSON RD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-2264',
        NULL,
        NULL,
        'LOAND # C289-B289-289A'
    ),
    (
        '61',
        NULL,
        'DOUG WHITNEY',
        '3951 EAST GRAND PLAINS RD',
        'ROSWELL',
        'NM',
        '88201',
        '575-622-8080',
        NULL,
        NULL,
        'LOAN # 254B'
    ),
    (
        '62',
        NULL,
        'DTMC LIMITED PARTNERSHIP',
        'PO BOX 3359',
        'ROSWELL',
        'NM',
        '88202',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '63',
        NULL,
        'DWIGHT MENEFEE',
        '446 WEST PEARSON RD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-7610',
        NULL,
        NULL,
        'BOARD MEMBER DISTRICT 4'
    ),
    (
        '64',
        NULL,
        'EARL GRASSIE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '65',
        NULL,
        'EARL S. CORN FARMS, INC.',
        'PO BOX 295',
        'DEXTER',
        'NM',
        '88230',
        '575-734-5887',
        '575-626-2590',
        NULL,
        'LOAN #A318'
    ),
    (
        '66',
        NULL,
        'EARTH WATER NEW MEXICO',
        '46 HENRY LANE',
        'LOVINGTON',
        'NM',
        '88260',
        '575-370-0047',
        NULL,
        NULL,
        'KELLY JAMES OWNER'
    ),
    (
        '67',
        NULL,
        'EDDY COUNTY TREASURER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '68',
        NULL,
        'ELMER BUCHHEIM',
        '7342 NORTH MAIN ST',
        'ROSWELL',
        'NM',
        '88201',
        '575.420-9796',
        NULL,
        NULL,
        NULL
    ),
    (
        '69',
        NULL,
        'ELMER DEAN SONS',
        'P.O. BOX 8106',
        'ROSWELL',
        'NM',
        '88202',
        '575-626-4709',
        NULL,
        NULL,
        'LOAN # E231-C231-D231'
    ),
    (
        '70',
        NULL,
        'FELIX FARMS,  L.P.',
        '3763 CROSSROADS',
        'ROSWELL',
        'NM',
        '88203',
        '575-622-0521',
        NULL,
        NULL,
        'LOAN # A274'
    ),
    (
        '71',
        NULL,
        'FIRST FEDERAL BANK',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '72',
        NULL,
        'FIRST NATIONAL BANK - ARTESIA',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '73',
        NULL,
        'FIRST NATIONAL BANK - ROSWELL',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '74',
        NULL,
        'FORREST TIRE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '75',
        NULL,
        'FRED HENNIGHAUSEN',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '76',
        NULL,
        'FRED NELSON FARMS',
        '3755 EAST GRAND PLAINS RD',
        'ROSWELL',
        'NM',
        '88203',
        '505-856-7430',
        NULL,
        NULL,
        'LOAN # 195C'
    ),
    (
        '77',
        NULL,
        'FREELAND REVOCABLE TRUST',
        'PO BOX 85',
        'DEXTER',
        'NM',
        '88230',
        '575-626-1898',
        NULL,
        NULL,
        NULL
    ),
    (
        '78',
        NULL,
        'FULLER SUPPLY CO., INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '79',
        NULL,
        'GARY EBERHART',
        '2898 WOODBINE WAY',
        'ROSWELL',
        'NM',
        '88203',
        NULL,
        '575-626-1165',
        NULL,
        NULL
    ),
    (
        '80',
        NULL,
        'GEORGE FAILING COMPANY',
        'PO BOX 872',
        'ENID',
        'OK',
        '73702',
        '580-234-4141',
        NULL,
        NULL,
        'ACCT # 77711'
    ),
    (
        '81',
        NULL,
        'GEORGE YOUNG SALES CO.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '82',
        NULL,
        'GLEN DAVID MILLER/SCHRIMSHER',
        '2609 GAYE DR.',
        'ROSWELL',
        'NM',
        '88201',
        '575-623-5732',
        NULL,
        NULL,
        'LOAN # A275-- %TED SCHRIMSHER 623-6868'
    ),
    (
        '83',
        NULL,
        'GLENN MARSHALL TRUST',
        '548 SHAWNEE RD',
        'DEXTER',
        'NM',
        '88230',
        '505-734-5810',
        NULL,
        NULL,
        'LOAN# 292A'
    ),
    (
        '84',
        NULL,
        'GOODE''S WELDING, INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '85',
        NULL,
        'GRASSIE FARMS, INC.',
        '686 EAST OJIBWA RD',
        'DEXTER',
        'NM',
        '88230',
        '505-626-3673',
        NULL,
        NULL,
        'LAN # 268A'
    ),
    (
        '86',
        NULL,
        'GREAT PLAINS METER',
        NULL,
        NULL,
        'NEB',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '87',
        NULL,
        'GREG ALPERS',
        '1909 WEST 27TH ST.',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-7438',
        NULL,
        NULL,
        'VICE CHAIRMAN OF THE BOARD, DISTRICT 1'
    ),
    (
        '88',
        NULL,
        'GREGORY ROCKHOUSE RANCH',
        NULL,
        'CARLSBAD,',
        'NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '89',
        NULL,
        'H.C. BERRY',
        'P.O. BOX 579',
        'DEXTER',
        'NM',
        '88230',
        '575-734-6333',
        NULL,
        NULL,
        'LN # 240D;F240;240E;240G'
    ),
    (
        '90',
        NULL,
        'HACH COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '91',
        NULL,
        'HAGERMAN IRRIGATION CO.',
        'PO BOX 507',
        'HAGERMAN',
        'NM',
        '88232',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '92',
        NULL,
        'HENNIGHAUSEN & OLSEN',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '93',
        NULL,
        'HERBERT AND SHEILA CORN',
        '163 EDEN VALLEY ROAD',
        'ROSWELL',
        'NM',
        '88201',
        '575-84-6060',
        NULL,
        NULL,
        'LOAN A347'
    ),
    (
        '94',
        NULL,
        'HINKLE HENSLEY SHANOR & MARTIN',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '95',
        NULL,
        'INK SPOT',
        '800 SOUTH MAIN ST',
        'ROSWELL',
        'NM',
        '88203',
        '575-622-5800',
        NULL,
        NULL,
        'PRINTER'
    ),
    (
        '96',
        NULL,
        'J. PHELPS WHITE, III',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '97',
        NULL,
        'JACK  JOY',
        'PO BOX 928',
        'ARTESIA',
        'NM',
        '88211-0928',
        '575-746-4593',
        NULL,
        NULL,
        'LOAN # A295'
    ),
    (
        '98',
        NULL,
        'JACK & DIANA JOY',
        '519 VOGEL ROAD',
        'ARTESIA',
        'NM',
        '88210',
        '575-746-4593',
        NULL,
        NULL,
        NULL
    ),
    (
        '99',
        NULL,
        'JACK WAIDE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '100',
        NULL,
        'JACKSON, COLEMAN',
        '72 WEST JACKSON RD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-2342',
        NULL,
        NULL,
        'LOAN # A298'
    ),
    (
        '101',
        NULL,
        'JAIME ARANDA',
        'PO BOX 134',
        'LAKE ARTHUR',
        'NM',
        '88253',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '102',
        NULL,
        'JAMES & CLAUDIA WAIDE',
        'PO BOX 2165',
        'ROSWELL',
        'NM',
        '88202',
        '575-622-3805',
        '575-626-3218',
        NULL,
        NULL
    ),
    (
        '103',
        NULL,
        'JAMES & WANDA FREELAND',
        'P.O. BOX 85',
        'DEXTER',
        'NM',
        '88230',
        '575-626-1636',
        '575-734-5046',
        NULL,
        'ADDRESS CHG REQUESTED 6/29/15'
    ),
    (
        '104',
        NULL,
        'JAMES FREELAND',
        'P.O. BOX 413',
        'DEXTER',
        'NM',
        '88230',
        '575-734-5758',
        '575-626-1636',
        NULL,
        NULL
    ),
    (
        '105',
        NULL,
        'JAMIE ARANDA',
        'P.O. BOX 134',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '505-420-2259',
        NULL,
        NULL,
        'LOAN # A301'
    ),
    (
        '106',
        NULL,
        'JANET BORBA',
        '3700 LOVERS LANE',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-0159',
        NULL,
        NULL,
        'CONSERVATION LOAN FUNDED 5/23/12'
    ),
    (
        '107',
        NULL,
        'JANIE PIRTLE JONES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '108',
        NULL,
        'JENNINGS & JENNINGS',
        '2109 FULKERSON DR.',
        'ROSWELL',
        'NM',
        '88203',
        '575-623-3522',
        NULL,
        NULL,
        'LOAN # 288A-B288'
    ),
    (
        '109',
        NULL,
        'JESSE FINCH',
        '29 LOS ALAMOS RD',
        'ROSWELL',
        'NM',
        '88203',
        '627-6418',
        '637-0040',
        NULL,
        NULL
    ),
    (
        '110',
        NULL,
        'JIM RICHARDSON',
        'RR 2 3500 SCHOOL RD',
        'ROSWELL',
        'NM',
        '88203',
        '575-317-9597',
        NULL,
        NULL,
        'BOARD OF DIRECTOR DISTRICT 2'
    ),
    (
        '111',
        NULL,
        'JOE D. DURAND',
        'PO BOX 171',
        'DEXTER',
        'NM',
        '88230',
        '575-734-5780',
        NULL,
        NULL,
        'LOAN # A302-B302'
    ),
    (
        '112',
        NULL,
        'JOHN AND MELINDA JACKSON',
        'PO BOX 177',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-6206',
        '575-365-2096',
        NULL,
        NULL
    ),
    (
        '113',
        NULL,
        'JOHN GRAY TRUST',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '114',
        NULL,
        'JOHN W. SHOMAKER, INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '115',
        NULL,
        'JOHN, JAMES BERRY AND BARBARA ROSS',
        'PO BOX 579',
        'DEXTER',
        'NM',
        '88230',
        '575-734-6333',
        '575-910-4286',
        NULL,
        'THIS LOAN WILL BE PAID BY JJM FARMS'
    ),
    (
        '116',
        NULL,
        'JOHNNY CROOK',
        '431 WALNUT DRAW',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-2348',
        NULL,
        NULL,
        'LOAN # A305'
    ),
    (
        '117',
        NULL,
        'JOHNNY W. JOY',
        '667 JOY RD',
        'LAKE ARTHUR',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '118',
        NULL,
        'JOHNSON 3 J FARM',
        NULL,
        'ARTESIA',
        'NM',
        NULL,
        '365-8709',
        NULL,
        NULL,
        'JIMMY JOHNSON''S PHONE NUMBER'
    ),
    (
        '119',
        NULL,
        'JUSTIN AND AMY MUNSON',
        '1804 WHITE MILL RD',
        'ROSWELL',
        'NM',
        '88203',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '120',
        NULL,
        'KELLEY DRILL COLLAR SERVICE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '121',
        NULL,
        'KEN AND CODY REVOCABLE TRUST',
        '6225 BAKER RD',
        'ROSWELL',
        'NM',
        '88203',
        '622-1616',
        NULL,
        NULL,
        NULL
    ),
    (
        '122',
        NULL,
        'KENNETH BAKER',
        '6225 BAKER RD.',
        'ROSWELL',
        'NM',
        '88201',
        '575-622-1616',
        NULL,
        NULL,
        'LOAN # 285A ALTERNATE PHON# 622-4692'
    ),
    (
        '123',
        NULL,
        'KENNETH BAKER',
        '6225 BAKER ROAD',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '124',
        NULL,
        'KENNETH WHITNEY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '125',
        NULL,
        'KERR/ FALLWELL',
        'P.O. BOX 807',
        'DEXTER',
        'NM',
        '88230',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '126',
        NULL,
        'LARRY & KATHY BAKER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '127',
        NULL,
        'LARRY WAGGONER',
        'P.O. Box 123',
        'Roswell',
        'NM',
        '88202-0123',
        '622 5555',
        NULL,
        NULL,
        NULL
    ),
    (
        '128',
        NULL,
        'LATIMER FARM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '129',
        NULL,
        'LE & JOAN ROTTMAN',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '130',
        NULL,
        'LIFE INVESTORS INSURANCE CO',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '131',
        NULL,
        'LINDA K TIDWELL',
        NULL,
        NULL,
        NULL,
        NULL,
        '575-365-6579',
        NULL,
        NULL,
        NULL
    ),
    (
        '132',
        NULL,
        'LOS SIETE EXPLORE/ WESTERN OIL',
        NULL,
        NULL,
        NULL,
        NULL,
        '626-5275',
        NULL,
        NULL,
        'CODY BURSON CONTACT'
    ),
    (
        '133',
        NULL,
        'LOU MCCREA',
        'PO BOX 3359',
        'ROSWELL',
        'NM',
        '88202-3359',
        '575-653-4241',
        NULL,
        NULL,
        'LOAN # 290A - %DAVID MCCREA CELL# 626-0801'
    ),
    (
        '134',
        NULL,
        'LYKINS TIRE COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '135',
        NULL,
        'MARLEY RANCHES LTD.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '136',
        NULL,
        'MAYBERRY INC.',
        '3302 W. RICHEY',
        'ARTESIA',
        'NM',
        '88210',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '137',
        NULL,
        'MAYES LUMBER CO., INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '138',
        NULL,
        'McCROMETER DIVISION',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '139',
        NULL,
        'MIKE FALLWELL',
        'PO BOX 807',
        'DEXTER',
        'NM',
        '88230',
        '575-626-3655',
        NULL,
        NULL,
        NULL
    ),
    (
        '140',
        NULL,
        'MIKE MCNALLEN',
        'PO Box 728',
        'Roswell',
        'NM',
        '88202',
        '505 622 1200',
        NULL,
        NULL,
        'Technical Business Services'
    ),
    (
        '141',
        NULL,
        'MORGAN NELSON',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '142',
        NULL,
        'MORWEST CORP',
        NULL,
        'MALJAMAR',
        'NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '143',
        NULL,
        'Nature''s Dairy',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '144',
        NULL,
        'NAVAJO REFINERY',
        NULL,
        'ARTESIA',
        'NM',
        '88210',
        '575-746-5248',
        NULL,
        NULL,
        'ROBERT BOANS'
    ),
    (
        '145',
        NULL,
        'NICKOLAS C. McMILLEN',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '146',
        NULL,
        'NM CHILD SUPPORT ENFORCEMENT',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '147',
        NULL,
        'NM DEPARTMENT OF LABOR',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '148',
        NULL,
        'NM INSTITUTE OF MINING & TECH.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '149',
        NULL,
        'NM INTERSTATE STREAM COMM.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '150',
        NULL,
        'NM MUTUAL CASUALTY COMPANY',
        'P.O. BOX 27805',
        'ALBUQUERQUE',
        'NM',
        '87125-7805',
        '505-343-7744',
        NULL,
        NULL,
        '1-800-788-8851'
    ),
    (
        '151',
        NULL,
        'NM STATE ENGINEER OFFICE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '152',
        NULL,
        'NORRIS AND SONS',
        '208 CHOCTAW ROAD',
        'HAGERMAN',
        'NM',
        '88232',
        '575-752-6677',
        NULL,
        NULL,
        'LOAN # 276A-C276-276B-RONALD NORRIS 752-6653 OR 626-1212'
    ),
    (
        '153',
        NULL,
        'OASIS DAIRY',
        NULL,
        'ROSWELL',
        'NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '154',
        NULL,
        'OFFICE MAX',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '155',
        NULL,
        'PATSY LYLES',
        'PO BOX 129',
        'LAKEWOOD',
        'NM',
        '88254',
        '575-457-2326',
        NULL,
        NULL,
        NULL
    ),
    (
        '156',
        NULL,
        'PATTY BARRESI',
        '3404 DOW DR',
        'ROSWELL',
        'NM',
        '88201',
        '575-317-3491',
        NULL,
        NULL,
        'EXECUTIVE SECRETARY FOR PVACD'
    ),
    (
        '157',
        NULL,
        'PAUL MAUPIN',
        '#10 SYCAMORE CT.',
        'ROSWELL',
        'N.M.',
        '88201',
        '575-914-0561',
        NULL,
        NULL,
        NULL
    ),
    (
        '158',
        NULL,
        'PAUL TAYLOR III & PAUL TAYLOR JR.',
        'PO BOX 344',
        'ROSWELL',
        'NM',
        '88202',
        '575-910-0438',
        NULL,
        NULL,
        NULL
    ),
    (
        '159',
        NULL,
        'PECOS VALLEY ARTESIAN CONS.',
        'PO BOX 1346',
        'ROSWELL',
        'NM',
        '88202',
        '575-622-7000',
        NULL,
        NULL,
        'STREET ADDY: 2303 EAST 2ND ST. FAX 575-622-7001'
    ),
    (
        '160',
        NULL,
        'PECOS VALLEY PUMP',
        NULL,
        'DEXTER',
        'NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '161',
        NULL,
        'Perry Toles',
        'P.O. Drawer 1300',
        'Roswell',
        'NM',
        '88202',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '162',
        NULL,
        'PIERRE FARMS LLC',
        NULL,
        NULL,
        NULL,
        NULL,
        '575-208-8176',
        NULL,
        NULL,
        NULL
    ),
    (
        '163',
        NULL,
        'PILAR & LINDA MUNOZ',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '164',
        NULL,
        'PIONEER BANK',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '165',
        NULL,
        'PIRTLE & SONS',
        '13 VISTA PARKWAY',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '166',
        NULL,
        'PIRTLE FARMS L.P.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '167',
        NULL,
        'PLATEAU WIRELESS-NM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '168',
        NULL,
        'PNM ELECTRIC & GAS SERVICES',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '169',
        NULL,
        'POWELL TIRE & SUPPLY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '170',
        NULL,
        'PRINCIPLE LIFE GROUP GRAND ISL',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '171',
        NULL,
        'PT PRODUCTIONS, INC',
        'PO BOX 344',
        'ROSWELL',
        'NM',
        '88202',
        '575-910-0438',
        NULL,
        NULL,
        NULL
    ),
    (
        '172',
        NULL,
        'PUBLIC EMPLOYEES RETIREMENT',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '173',
        NULL,
        'PURCELL FARMS',
        '#8 SOLANA LANE',
        'ROSWELL',
        'NM',
        '88201',
        '575-626-4733',
        NULL,
        NULL,
        NULL
    ),
    (
        '174',
        NULL,
        'PVACD',
        'P.O. BOX 1346',
        'ROSWELL',
        'NM',
        '88202',
        '575-622-7000',
        '575-626-4756',
        NULL,
        NULL
    ),
    (
        '175',
        NULL,
        'QWEST',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '176',
        NULL,
        'RAFTER 4 OF DEXTER, LLC',
        '1804 WHITE MILL RD',
        'ROSWELL',
        'NM',
        '88203',
        '575-910-2830',
        '575-626-0538',
        NULL,
        'JUSTIN AND AMY MUNSON'
    ),
    (
        '177',
        NULL,
        'RANDALL S. WILLIS',
        '182 ANASAZI RD',
        'DEXTER',
        'NM',
        '88230',
        '575-625-8833',
        NULL,
        NULL,
        'LN # B260'
    ),
    (
        '178',
        NULL,
        'RANDY JENNINGS',
        '3209 LaQuinta',
        'ROSWELL',
        'NM',
        '88203',
        '575-626-7343',
        NULL,
        NULL,
        'LOAN #A300'
    ),
    (
        '179',
        NULL,
        'RAQUEL PLATT',
        '7366 VINEYARD RD',
        'DEXTER',
        'NM',
        '88230',
        '575-734-5796',
        NULL,
        NULL,
        'LOAN # 198D'
    ),
    (
        '180',
        NULL,
        'RAYMOND NARANJO',
        '313 CAPITAN RD',
        'ROSWELL',
        'NM',
        '88201',
        '575-623-9145',
        NULL,
        NULL,
        'LOAN #D236- % CHRIS NARANJO'
    ),
    (
        '181',
        NULL,
        'RICHARD (DICK) SMITH',
        '3730 SPRING RIVER RD',
        'ROSWELL',
        'NM',
        '88203',
        '575-626-1356',
        NULL,
        NULL,
        'BOARD MEMBER DISTRICT 2'
    ),
    (
        '182',
        NULL,
        'RICHARD A SIMMS',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '183',
        NULL,
        'ROBERT & CHERI BURSON',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'GYM REAL ESTATE, LLC'
    ),
    (
        '184',
        NULL,
        'ROBERT BREWER',
        '7424 CHEROKEE RD.',
        'HAGERMAN',
        'NM',
        '88232',
        '575-734-5619',
        NULL,
        NULL,
        'LN # E19'
    ),
    (
        '185',
        NULL,
        'ROBERT C. CALLAWAY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '186',
        NULL,
        'ROBERT S. BREWER',
        '7424 CHEROKEE ROAD',
        'HAGERMAN',
        'NM',
        '88232',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '187',
        NULL,
        'Robert Schoolcraft',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '188',
        NULL,
        'ROBERT ST. LOUIS',
        'PO BOX 2283',
        'ROSWELL',
        'NM',
        '88202',
        '575-625-2545',
        NULL,
        NULL,
        'LOAN # 250C'
    ),
    (
        '189',
        NULL,
        'ROGERS, INC.',
        '#52 ROGERS DRIVE',
        'ARTESIA',
        'NM',
        '88210',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '190',
        NULL,
        'ROSWELL DAILY RECORD',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '191',
        NULL,
        'ROSWELL LIVESTOCK & FARM',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '192',
        NULL,
        'ROSWELL LUMBER COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '193',
        NULL,
        'ROSWELL READY MIX',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '194',
        NULL,
        'ROSWELL SEED COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '195',
        NULL,
        'ROSWELL TIRE & APPLIANCE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '196',
        NULL,
        'ROSWELL WINLECTRIC CO.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '197',
        NULL,
        'RUTH CORN, INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '198',
        NULL,
        'RYAN PERRY',
        'P.O. BOX 4301',
        'ROSWELL',
        'NM',
        '88202',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '199',
        NULL,
        'SCRIMSHER FARMS',
        '2609 GAYE DRIVE',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '200',
        NULL,
        'SEVEN RIVERS INC.',
        NULL,
        NULL,
        NULL,
        NULL,
        '746-7237',
        NULL,
        NULL,
        'MIKE PRUDE- CONTACT'
    ),
    (
        '201',
        NULL,
        'SIDNEY BREWER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '202',
        NULL,
        'SOUTHWEST BEARING COMPANY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '203',
        NULL,
        'SOUTHWIND DAIRY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        'NEW INSTALL'
    ),
    (
        '204',
        NULL,
        'SPENCE FARMS',
        '8653 SPENCE RD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-8892',
        NULL,
        NULL,
        NULL
    ),
    (
        '205',
        NULL,
        'SPITZER AUTOMOTIVE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '206',
        NULL,
        'STERRETT FARMS',
        '3834 EAST GRAND PLAINS RD',
        'ROSWELL',
        'NM',
        '88203',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '207',
        NULL,
        'STERRETT LAND & CATTLE, LTD.',
        '3207 WHITE MILL RD',
        'ROSWELL',
        'NM',
        '88201',
        NULL,
        NULL,
        NULL,
        'LOAN # 244C- 244B'
    ),
    (
        '208',
        NULL,
        'Stuart Taylor',
        '1505 Fowler Rd.',
        'Roswell',
        'NM',
        '88201',
        '1-575-626-3664',
        NULL,
        NULL,
        NULL
    ),
    (
        '209',
        NULL,
        'SYDNEY BREWER',
        '7424 CHEROKEE ROAD',
        'HAGERMAN',
        'NM',
        '88232',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '210',
        NULL,
        'TAXATION & REVENUE DEPT.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '211',
        NULL,
        'TCS/ TRUCKING CONTRACTING SERVICES',
        'PO BOX 878',
        'CARLSBAD',
        'NM',
        '88221',
        '432-557-7202',
        NULL,
        NULL,
        NULL
    ),
    (
        '212',
        NULL,
        'TECHNICAL BUSINESS SERVICE',
        'P.O. BOX 728',
        'ROSWELL',
        'NM',
        '88202',
        '505-317-9470',
        NULL,
        NULL,
        'MIKE MCNALLEN- IT PERSON'
    ),
    (
        '213',
        NULL,
        'TERI WIER',
        'PO BOX 16',
        'DEXTER',
        'NM',
        '88230',
        '575-626-0285',
        NULL,
        NULL,
        NULL
    ),
    (
        '214',
        NULL,
        'TERI WIER',
        'P.O. BOX 16',
        'DEXTER',
        'NM',
        '88230',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '215',
        NULL,
        'TEST DRIVE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '216',
        NULL,
        'THOMAS VISSER',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '217',
        NULL,
        'TIM POLLARD',
        '435 JICARRILLA RD',
        'HAGERMAN',
        'NM',
        '88232',
        '575-399-3598',
        NULL,
        NULL,
        NULL
    ),
    (
        '218',
        NULL,
        'TOLES PERRY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '219',
        NULL,
        'TOM BARRESI',
        '3404 DOW DR.',
        'ROSWELL',
        'NM',
        '88201',
        '575-625-0611',
        NULL,
        NULL,
        NULL
    ),
    (
        '220',
        NULL,
        'TRAVIS HICKS',
        '4105 WHITEMILL RD',
        'ROSWELL',
        'NM',
        '88203',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '221',
        NULL,
        'TRINITY CHAPEL ASSEMBLY OF GOD',
        NULL,
        'ARTESIA',
        'NM',
        NULL,
        '575-613-2402',
        NULL,
        NULL,
        'PASTOR BOBBY ARGO AND MAINT: RICHARD BOHATY'
    ),
    (
        '222',
        NULL,
        'U.S. DEPT. OF INTERIOR - USGS,',
        'BOX 70934',
        'CHARLOTTE',
        'NC',
        '28272-0934',
        '505-830-7906',
        NULL,
        NULL,
        'JOINT STUDIES'
    ),
    (
        '223',
        NULL,
        'UNIFIRST HOLDINGS L.P.',
        'P.O. BOX 844',
        'CLOVIS',
        'NM',
        '88101',
        '5756-763-4441',
        NULL,
        NULL,
        'ACCT # 254058'
    ),
    (
        '224',
        NULL,
        'VALLEY BANK OF COMMERCE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '225',
        NULL,
        'W & B MENEFEE, INC.',
        'PO BOX 1181',
        'ARTESIA',
        'NM',
        '88211-1181',
        '575-748-3765',
        NULL,
        NULL,
        'LOAN # A304 CELL 365-7544'
    ),
    (
        '226',
        NULL,
        'W.I. JOHNSON',
        '202 ESPUELA ROAD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '227',
        NULL,
        'WAIDE IRRIGATION',
        'P.O. BOX 516',
        'HAGERMAN',
        'NM',
        '88232',
        '622-4416',
        NULL,
        NULL,
        NULL
    ),
    (
        '228',
        NULL,
        'WALTER GRASSIE',
        'PO BOX 93',
        'DEXTER',
        'NM',
        '88230',
        '575-626-1367',
        NULL,
        NULL,
        'LOAN # A279'
    ),
    (
        '229',
        NULL,
        'WALTER GRASSIE FARMS, LLC',
        'PO BOX 93',
        'DEXTER',
        'NM',
        '88230',
        '575-317-9419',
        NULL,
        NULL,
        'SYBIL- 575-626-1637 MARY- margaretsusan2003@yahoo.com'
    ),
    (
        '230',
        NULL,
        'WAYNON LYLES/Barry Lyles',
        '77 EAST PEARSON RD',
        'LAKE ARTHUR',
        'NM',
        '88253',
        '575-365-2275',
        NULL,
        NULL,
        'LOAN # J76 Cross L Farms'
    ),
    (
        '231',
        NULL,
        'WELLS FARGO BANK',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '232',
        NULL,
        'WESLEY MENEFEE',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '233',
        NULL,
        'WESLEY NEEDHAM, JR.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '234',
        NULL,
        'WESTERN BANK',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '235',
        NULL,
        'WHITNEY FARMS, LTD',
        '5042 WHITNEY LANE',
        'ROSWELL',
        'NM',
        '88203',
        '575-420-3000',
        NULL,
        NULL,
        NULL
    ),
    (
        '236',
        NULL,
        'WORKERS'' COMPENSATION ADMIN.',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '237',
        NULL,
        'XCEL ENERGY',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        '238',
        NULL,
        'ZAN KING',
        '450 E CHICKASAW RD.',
        'HAGERMAN',
        'NM',
        '88232',
        '575-752-6647',
        NULL,
        NULL,
        'LOAN # A272-B272'
    ),
    (
        '239',
        NULL,
        'Zan or Kavan King',
        '454 Chickasaw Rd',
        'Hagerman',
        'NM',
        '88232',
        '575-752-3508',
        '575-840-8614',
        NULL,
        'phone numbers are Kavans'''
    ) ON CONFLICT (id) DO NOTHING;

SELECT
    setval ('public."LandOwners_id_seq"', 239, true);
