version: "3.9"
services:
  frontend:
    image: "node:latest"
    working_dir: /home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/home/node/app
    command: npm start

  
  

 
